FROM mysql:8.0

# Copy initialization scripts
COPY mysql/init.sql /docker-entrypoint-initdb.d/01-init.sql
COPY mysql/dev_db.sql /docker-entrypoint-initdb.d/02-dev_db.sql

# Set default environment variables
ENV MYSQL_ROOT_PASSWORD=MB_R00t_P@ss_2024!
ENV MYSQL_DATABASE=mbti_employees
ENV MYSQL_USER=mbti_admin
ENV MYSQL_PASSWORD=Training_DB_2024
