// WKT Datenpflege Standardwarenkorb
const PKW_LOOP_ARRAY = ["Gruppe", 
    "Bildtafel", 
    "Modul", 
    "WK Pos", 
    "Benennung Deutsch", 
    "WK", 
    "BEV", 
    "Allg V1 V", 
    "Allg V1 N", 
    "Allg V2 V", 
    "Allg V3 V", 
    "Allg V2 N", 
    "Allg V3 N", 
    "D V1 V", 
    "D V1 N", 
    "D V2 V", 
    "D V3 V", 
    "D V2 N", 
    "D V3 N", 
    "Val V1 V", 
    "ET V1 V", 
    "Val V1 N", 
    "ET V1 N", 
    "F V2 V", 
    "F V3 V", 
    "F V2 N", 
    "F V3 N", 
    "Bel V2 V", 
    "Bel V3 V", 
    "Bel V2 N", 
    "Bel V3 N", 
    "NL V2 V", 
    "NL V3 V", 
    "NL V2 N", 
    "NL V3 N", 
    "I V1 V", 
    "I V1 N", 
    "I V2 V", 
    "I V3 V", 
    "I V2 N", 
    "I V3 N", 
    "CH V1 V", 
    "CH V1 N", 
    "CH V2 V", 
    "CH V3 V", 
    "CH V2 N", 
    "CH V3 N", 
    "E V1 V", 
    "E V1 N", 
    "E V2 V", 
    "E V3 V", 
    "E V2 N", 
    "E V3 N", 
    "P V2 V", 
    "P V3 V", 
    "P V2 N", 
    "P V3 N", 
    "A V2 V", 
    "A V3 V", 
    "A V2 N", 
    "A V3 N", 
    "UK V1 V", 
    "UK V1 N", 
    "UK V2 V", 
    "UK V3 V", 
    "UK V2 N", 
    "UK V3 N", 
    "AUS V1 V", 
    "AUS V1 N", 
    "KR V1 V", 
    "KR V1 N", 
    "KR V2 V", 
    "KR V3 V", 
    "KR V2 N", 
    "KR V3 N", 
    "GR V1 V", 
    "GR V1 N", 
    "DU V1 V", 
    "DU V1 N"
];

const EQ_LOOP_ARRAY = ["Gruppe", 
    "Bildtafel", 
    "Modul", 
    "WK Pos", 
    "Benennung Deutsch", 
    "WK", 
    "BEV", 
    "Allg V1 V", 
    "Allg V1 N", 
    "Allg V2 V", 
    "Allg V3 V", 
    "Allg V2 N", 
    "Allg V3 N", 
    "D V1 V", 
    "D V1 N", 
    "D V2 V", 
    "D V3 V", 
    "D V2 N", 
    "D V3 N", 
    "Val V1 V", 
    "ET V1 V", 
    "Val V1 N", 
    "ET V1 N", 
    "F V2 V", 
    "F V3 V", 
    "F V2 N", 
    "F V3 N", 
    "Bel V2 V", 
    "Bel V3 V", 
    "Bel V2 N", 
    "Bel V3 N", 
    "NL V2 V", 
    "NL V3 V", 
    "NL V2 N", 
    "NL V3 N", 
    "I V1 V", 
    "I V1 N", 
    "I V2 V", 
    "I V3 V", 
    "I V2 N", 
    "I V3 N", 
    "CH V1 V", 
    "CH V1 N", 
    "CH V2 V", 
    "CH V3 V", 
    "CH V2 N", 
    "CH V3 N", 
    "E V1 V", 
    "E V1 N", 
    "A V2 V", 
    "A V3 V", 
    "A V2 N", 
    "A V3 N", 
    "UK V1 V", 
    "UK V1 N", 
    "UK V2 V", 
    "UK V3 V", 
    "UK V2 N", 
    "UK V3 N", 
    "AUS V1 V", 
    "AUS V1 N", 
    "KR V1 V", 
    "KR V1 N", 
    "KR V2 V", 
    "KR V3 V", 
    "KR V2 N", 
    "KR V3 N", 
    "DU V1 V", 
    "DU V1 N"
];

// TODO: Must be changed
const OTHER_LOOP_ARRAY = [
    "Gruppe",    "Bildtafel", "Modul",     "WK Pos",    "Benennung Deutsch",
    "WK",        "BEV",       "Allg V1 V", "Allg V1 N", "Allg V2 V", 
    "Allg V3 V", "Allg V2 N", "Allg V3 N", "D V1 V",    "D V1 N",    
    "D V2 V",    "D V3 V",    "D V2 N",    "D V3 N",    "Val V1 V",
    "ET V1 V",   "Val V1 N",  "ET V1 N",   "F V2 V",    "F V3 V",    
    "F V2 N",    "F V3 N",    "Bel V2 V",  "Bel V3 V",  "Bel V2 N",  
    "Bel V3 N",  "NL V2 V",   "NL V3 V",   "NL V2 N",   "NL V3 N",   
    "I V1 V",    "I V1 N",    "I V2 V",    "I V3 V",    "I V2 N",    
    "I V3 N",    "CH V1 V",   "CH V1 N",   "CH V2 V",   "CH V3 V",
    "CH V2 N",   "CH V3 N",   "E V1 V",    "E V1 N",    "E V2 V",    
    "E V3 V",    "E V2 N",    "E V3 N",    "P V2 V",    "P V3 V",    
    "P V2 N",    "P V3 N",    "A V2 V",    "A V3 V",    "A V2 N",
    "A V3 N",    "UK V1 V",   "UK V1 N",   "UK V2 V",   "UK V3 V",   
    "UK V2 N",   "UK V3 N",   "AUS V1 V",  "AUS V1 N",  "KR V1 V",   
    "KR V1 N",   "KR V2 V",   "KR V3 V",   "KR V2 N",   "KR V3 N",
    "GR V1 V",   "GR V1 N",   "DU V1 V",   "DU V1 N",   "D V1",      
    "D V2",      "D V3",      
    ];

module.exports = {PKW_LOOP_ARRAY,EQ_LOOP_ARRAY,OTHER_LOOP_ARRAY};